"use client";
import { useRouter } from "next/navigation";

const MONO = "'Space Mono','Courier New',monospace";
const GROTESK = "'Space Grotesk',-apple-system,BlinkMacSystemFont,sans-serif";

const sections = [
  {
    title: "1. Introduction and Acceptance",
    body: `MoggedAI ("Company," "we," "us," or "our") operates the website moggedai.com and provides an SMS-based AI accountability service (the "Service"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information.

BY ACCESSING OR USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THIS PRIVACY POLICY IN ITS ENTIRETY. IF YOU DO NOT AGREE, YOU MUST IMMEDIATELY CEASE USE OF THE SERVICE.

This policy is incorporated into and subject to our Terms of Service.`,
  },
  {
    title: "2. Information We Collect",
    body: `We collect only the information necessary to provide the Service:

ACCOUNT INFORMATION
• Name and email address, collected via our authentication provider (Clerk)
• Account creation date and login activity

CONTACT INFORMATION
• Mobile phone number you voluntarily provide during setup
• You represent that the phone number you provide belongs to you and that you are authorized to receive SMS messages at that number

HABIT AND PREFERENCE DATA
• Habit names, goals, and descriptions you voluntarily enter
• Personal context you choose to share (your "why," stated excuses, stakes)
• Schedule preferences (active hours, message frequency, timezone)
• Coach style preference

USAGE DATA
• Messages sent and received through the Service
• Habit completion logs and timestamps
• Streak and statistics data derived from your activity
• IP address and general browser/device information for security purposes

We do not collect payment information, Social Security numbers, government IDs, financial data, or sensitive health information. You should not submit any such information through the Service.`,
  },
  {
    title: "3. How We Use Your Information",
    body: `We use collected information solely for the following purposes:

• Delivering the core Service: sending AI-generated accountability SMS messages to your phone number on your chosen schedule
• Personalizing AI-generated messages based on context you voluntarily provide
• Maintaining your account, preferences, and usage history
• Calculating streaks and completion statistics displayed in your dashboard
• Communicating service-related updates, changes, or notices
• Enforcing our Terms of Service and protecting the security of the Service
• Complying with legal obligations

WE DO NOT:
• Sell, rent, lease, or trade your personal information to any third party for marketing purposes
• Use your personal information to build advertising profiles
• Share your phone number with third parties for their own marketing
• Use your information for any purpose not stated in this policy without your explicit consent`,
  },
  {
    title: "4. SMS Messaging and TCPA Compliance",
    body: `CONSENT
By providing your mobile phone number and affirmatively checking the consent checkbox during setup, you provide express written consent to receive recurring automated SMS text messages from MoggedAI at the number provided. This consent is not a condition of purchasing any goods or services.

NATURE OF MESSAGES
Messages are sent using automated technology. Message content is generated by artificial intelligence and personalized based on data you provide. Message frequency depends on the schedule you select (ranging from every 30 minutes to every 3 hours during your chosen active hours).

COSTS
Message and data rates from your mobile carrier may apply. MoggedAI is not responsible for any charges incurred from your carrier.

OPT-OUT
You may revoke consent and opt out of all SMS messages at any time by:
• Texting STOP to +1 (844) 991-1147
• Updating your preferences in the dashboard

Upon receipt of STOP, we will send one final confirmation message and cease all further SMS communications. Opting out does not delete your account.

HELP
Text HELP to +1 (844) 991-1147 for assistance, or email wasseem800@gmail.com.

YOUR REPRESENTATIONS
By providing your phone number, you represent and warrant that: (a) you are the account holder or have explicit authorization from the account holder to provide the number; (b) you are 18 years of age or older; (c) you have the legal capacity to consent to these terms.`,
  },
  {
    title: "5. How We Share Your Information",
    body: `We do not sell your personal information. We share information only in the following limited circumstances:

SERVICE PROVIDERS
We share data with third-party vendors who assist in operating the Service, under confidentiality obligations and only to the extent necessary:
• Clerk, Inc. — authentication and identity management
• Twilio Inc. — SMS delivery infrastructure
• Railway Technologies — cloud hosting and database
• Google LLC (Gemini API) — AI message generation

These providers process your data only as directed by us and are contractually prohibited from using it for their own purposes.

LEGAL REQUIREMENTS
We may disclose your information if required to do so by law, regulation, legal process, or governmental request, or to protect the rights, property, or safety of MoggedAI, our users, or others.

BUSINESS TRANSFERS
In the event of a merger, acquisition, sale of assets, or bankruptcy, your information may be transferred as a business asset. We will notify you via email or prominent notice on the Service prior to any such transfer.

AGGREGATE DATA
We may share anonymized, aggregated, non-personally identifiable data for business or research purposes.

We will not share your personal information for any other purpose without your explicit prior consent.`,
  },
  {
    title: "6. Data Retention",
    body: `We retain your personal information for as long as your account remains active and as reasonably necessary to provide the Service.

Upon account deletion:
• Personal identifiers (name, email, phone number) will be deleted within 30 days
• Anonymized usage data (completion counts, streak history) may be retained indefinitely in non-identifiable form
• SMS message logs may be retained for up to 90 days for legal compliance purposes, then deleted
• Backups may retain data for up to 60 additional days after deletion from active systems

You may request deletion of your data at any time by contacting wasseem800@gmail.com. We will respond within 30 days.`,
  },
  {
    title: "7. Data Security",
    body: `We implement commercially reasonable technical and organizational security measures to protect your information, including:

• Encrypted data transgoal (TLS/HTTPS)
• Access controls limiting employee access to personal data
• Secure third-party infrastructure (Railway, Clerk)
• Regular review of data handling practices

HOWEVER, NO METHOD OF TRANSGOAL OVER THE INTERNET OR ELECTRONIC STORAGE IS 100% SECURE. WE CANNOT GUARANTEE ABSOLUTE SECURITY OF YOUR DATA. BY USING THE SERVICE, YOU ACKNOWLEDGE AND ACCEPT THIS RISK.

In the event of a data breach that affects your personal information, we will notify you as required by applicable law.`,
  },
  {
    title: "8. Disclaimer Regarding AI-Generated Content",
    body: `THE SMS MESSAGES YOU RECEIVE ARE GENERATED BY ARTIFICIAL INTELLIGENCE AND ARE PROVIDED FOR MOTIVATIONAL AND ACCOUNTABILITY PURPOSES ONLY.

AI-generated content does not constitute professional advice of any kind, including but not limited to medical, psychological, psychiatric, nutritional, fitness, legal, or financial advice. The messages are not a substitute for consultation with qualified professionals.

WE EXPRESSLY DISCLAIM ANY LIABILITY ARISING FROM:
• Reliance on AI-generated message content
• Emotional distress or psychological harm allegedly caused by message tone or content
• Any outcomes (positive or negative) related to habits tracked through the Service
• Inaccurate, inappropriate, or offensive AI-generated content

If you are experiencing a mental health crisis, please contact the 988 Suicide and Crisis Lifeline by dialing or texting 988, or contact emergency services.`,
  },
  {
    title: "9. Children's Privacy",
    body: `The Service is not directed to individuals under the age of 18. We do not knowingly collect personal information from anyone under 18. If we become aware that we have collected personal information from a minor, we will take immediate steps to delete such information.

If you believe we have inadvertently collected information from a minor, contact us immediately at wasseem800@gmail.com.`,
  },
  {
    title: "10. Your Rights and Choices",
    body: `You have the following rights regarding your personal information:

ACCESS: You may request a copy of the personal data we hold about you.

CORRECTION: You may update inaccurate information directly in your dashboard or by contacting us.

DELETION: You may request deletion of your account and personal data.

OPT-OUT OF SMS: Text STOP to +1 (844) 991-1147 at any time.

DATA PORTABILITY: You may request your data in a portable format.

To exercise any of these rights, email wasseem800@gmail.com. We will respond within 30 days. We may require identity verification before fulfilling requests.

We will not discriminate against you for exercising any of these rights.`,
  },
  {
    title: "11. Limitation of Liability",
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, MOGGEDAI AND ITS OWNERS, OPERATORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO: LOSS OF PROFITS, LOSS OF DATA, LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE, OR SYSTEM FAILURE.

OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THIS POLICY OR THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNT YOU PAID US IN THE SIX MONTHS PRIOR TO THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100.00).

SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU IN FULL.`,
  },
  {
    title: "12. Indemnification",
    body: `You agree to indemnify, defend, and hold harmless MoggedAI and its owners, officers, employees, and agents from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or related to:

• Your use or misuse of the Service
• Your violation of this Privacy Policy or our Terms of Service
• Your violation of any applicable law or regulation
• Your provision of false or inaccurate information
• Any content you submit through the Service
• Claims by third parties that your use of the Service harmed them`,
  },
  {
    title: "13. Dispute Resolution and Arbitration",
    body: `PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS.

BINDING ARBITRATION
Any dispute, claim, or controversy arising out of or relating to this Privacy Policy, the Service, or your use thereof shall be resolved exclusively through binding individual arbitration, not in court, except as provided below.

CLASS ACTION WAIVER
YOU AND MOGGEDAI AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE PROCEEDING. The arbitrator may not consolidate more than one person's claims.

EXCEPTIONS
Either party may seek emergency injunctive relief in a court of competent jurisdiction to prevent irreparable harm pending arbitration.

GOVERNING LAW
This Privacy Policy and any disputes arising hereunder shall be governed by the laws of the United States, without regard to conflict of law principles.`,
  },
  {
    title: "14. Third-Party Links",
    body: `The Service may contain links to third-party websites or services. We are not responsible for the privacy practices or content of those third parties. We encourage you to review the privacy policies of any third-party sites you visit.`,
  },
  {
    title: "15. Changes to This Policy",
    body: `We reserve the right to modify this Privacy Policy at any time. We will provide notice of material changes by:
• Posting the updated policy on this page with a revised "Last Updated" date
• Sending an email to the address associated with your account (for significant changes)

Your continued use of the Service after the effective date of any changes constitutes your acceptance of the revised policy. If you do not agree to the updated policy, you must stop using the Service.`,
  },
  {
    title: "16. Contact Information",
    body: `For privacy-related questions, requests, or concerns:

MoggedAI
Operator: Wasseem Dabbas
Email: wasseem800@gmail.com
Website: moggedai.com

We aim to respond to all privacy inquiries within 30 days.`,
  },
];

export default function PrivacyPage() {
  const router = useRouter();

  return (
    <div style={{ minHeight: "100vh", background: "var(--c-root)", color: "var(--c-text)", fontFamily: GROTESK }}>
      <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet" />

      <nav style={{ position: "sticky", top: 0, zIndex: 50, background: "var(--c-nav)", borderBottom: "1px solid var(--c-border)", padding: "0 1.5rem", backdropFilter: "blur(8px)" }}>
        <div style={{ maxWidth: 720, margin: "0 auto", height: 52, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <button onClick={() => router.push("/")} style={{ background: "none", border: "none", cursor: "pointer", fontFamily: MONO, fontSize: "0.85rem", letterSpacing: "0.05em", color: "var(--c-text)" }}>
            MOGGED<span style={{ color: "#0ea5e9" }}>AI</span>
          </button>
          <button onClick={() => router.back()} style={{ background: "none", border: "1px solid var(--c-border)", color: "var(--c-text3)", fontFamily: MONO, fontSize: "0.6rem", letterSpacing: "0.1em", padding: "0.35rem 0.75rem", cursor: "pointer" }}>
            ← BACK
          </button>
        </div>
      </nav>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "3rem 1.5rem 5rem" }}>
        <div style={{ fontFamily: MONO, fontSize: "0.6rem", color: "#0ea5e9", letterSpacing: "0.25em", marginBottom: "0.75rem" }}>LEGAL</div>
        <h1 style={{ fontFamily: MONO, fontWeight: 700, fontSize: "clamp(1.4rem,4vw,2rem)", marginBottom: "0.5rem", color: "var(--c-text)" }}>
          Privacy Policy
        </h1>
        <p style={{ fontFamily: MONO, fontSize: "0.65rem", color: "var(--c-text3)", marginBottom: "0.5rem", letterSpacing: "0.1em" }}>
          Last updated: April 12, 2025
        </p>
        <p style={{ fontFamily: GROTESK, fontSize: "0.85rem", color: "var(--c-text3)", marginBottom: "3rem", lineHeight: 1.7, padding: "1rem", background: "var(--c-s1)", borderLeft: "3px solid #0ea5e9" }}>
          This Privacy Policy governs your use of moggedai.com and the MoggedAI SMS service. By using the Service, you agree to the collection and use of information as described herein. Please read this policy carefully before using the Service.
        </p>

        {sections.map((section) => (
          <div key={section.title} style={{ marginBottom: "2.5rem" }}>
            <h2 style={{ fontFamily: MONO, fontWeight: 700, fontSize: "0.85rem", letterSpacing: "0.1em", color: "#0ea5e9", marginBottom: "0.85rem" }}>
              {section.title}
            </h2>
            <div style={{ fontSize: "0.9rem", color: "var(--c-text2)", lineHeight: 1.85, whiteSpace: "pre-line" }}>
              {section.body}
            </div>
          </div>
        ))}

        <div style={{ marginTop: "3rem", padding: "1.25rem", border: "1px solid var(--c-border)", background: "var(--c-s1)" }}>
          <p style={{ fontFamily: MONO, fontSize: "0.6rem", color: "var(--c-text3)", letterSpacing: "0.1em", margin: 0, lineHeight: 1.8 }}>
            This Privacy Policy was last reviewed and updated on April 12, 2025. If you have any questions, contact wasseem800@gmail.com.
          </p>
        </div>
      </div>
    </div>
  );
}
