"use client";
import { useRouter } from "next/navigation";

const mono = "'Space Mono','Courier New',monospace";
const C = { bg: "#080808", text: "#f0f0f0", red: "#dc2626", muted: "#444", border: "#1a1a1a", card: "#0d0d0d" };

const STEPS = [
  {
    n: "01",
    title: "Set your habits",
    sub: "2 minutes to set up. Forever to benefit.",
    body: "Pick up to 5 habits you need to stay on top of. Gym, studying, working on your project, meditating — anything. We have common presets or you can type your own. You can always add or remove habits from your dashboard later.",
    sms: null,
  },
  {
    n: "02",
    title: "Choose how you want to be coached",
    sub: "Your coach style shapes every single message.",
    body: "Pick from three modes:\n\nBrutal — No mercy. Gets in your face. Zero sympathy for excuses.\n\nDirect — Clear and no-nonsense. Just the facts and what you need to do.\n\nMotivating — Intense but positive. Pushes you forward with energy.",
    sms: null,
  },
  {
    n: "03",
    title: "Set your active hours",
    sub: "We only text during your window.",
    body: "Tell us when to start and when to stop. We'll only text you during those hours in your local timezone. Set how often you want check-ins — every 30 minutes, every hour, or every few hours. Your timezone is auto-detected.",
    sms: null,
  },
  {
    n: "04",
    title: "Get texted all day",
    sub: "Personalized, AI-generated. Never the same message twice.",
    body: "We rotate through your habits and send unique check-in texts generated by AI. Every message references your specific habit and is written in your coach style. We pick whichever habit was checked in on least recently, so nothing gets ignored.",
    sms: {
      from: "You said you'd work on the side project today. Have you touched it yet?",
      reply: null,
    },
  },
  {
    n: "05",
    title: 'Reply "done" to mark it complete',
    sub: "That's the whole interaction.",
    body: "When you finish a habit, just text back 'done'. We log it, update your streak, and your coach responds. The whole thing takes 3 seconds. No app, no logging in, no dashboard.",
    sms: {
      from: "You said you'd work on the side project today. Have you touched it yet?",
      reply: "done just shipped the new feature",
      response: "5 day streak. keep building. this is how it gets done.",
    },
  },
  {
    n: "06",
    title: "No reply? We follow up.",
    sub: "5 minutes. Every time.",
    body: "If you don't reply within 5 minutes, we send a follow-up. Can't ignore us. This is the feature that actually makes it work — most accountability tools let you ghost them. We don't.",
    sms: {
      from: "Did you hit the gym this morning? Still waiting.",
      reply: null,
      followup: "That's 5 minutes. Still nothing. Get up.",
    },
  },
  {
    n: "07",
    title: "Talk back. The AI responds.",
    sub: "Full two-way coaching over SMS.",
    body: "Text us anything — excuses, questions, updates. Our AI coach reads your message and fires back in your style. It's not a bot giving canned responses. It's a real conversation that keeps you accountable.",
    sms: {
      from: "Have you meditated today?",
      reply: "I've been too stressed to meditate",
      response: "That's backwards. You meditate because you're stressed. Stop talking about it.",
    },
  },
  {
    n: "08",
    title: "Track your streaks",
    sub: "Momentum is the whole game.",
    body: "Every time you reply 'done', your streak grows. Text STREAK anytime to see all your current streaks. Text HABITS to see your completion counts. Your dashboard shows all your stats in one place.",
    sms: {
      from: null,
      reply: "streak",
      response: "💪 Gym: 12 day streak\n📚 Study: 4 day streak\n🚀 Side Project: 7 day streak",
    },
  },
];

export default function HowItWorks() {
  const router = useRouter();

  return (
    <div style={{ minHeight: "100vh", background: C.bg, color: C.text, fontFamily: mono }}>
      {/* Nav */}
      <nav style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "1rem 1.5rem", borderBottom: `1px solid rgba(220,38,38,0.2)`, background: "rgba(8,8,8,0.97)", position: "sticky", top: 0, zIndex: 10 }}>
        <div style={{ fontSize: "1.1rem", fontWeight: "700", letterSpacing: "0.15em", cursor: "pointer" }} onClick={() => router.push("/")}>
          MOGGED<span style={{ color: C.red }}>AI</span>
        </div>
        <button
          style={{ background: C.red, border: "none", color: "#fff", padding: "0.5rem 1.25rem", fontSize: "0.7rem", letterSpacing: "0.1em", cursor: "pointer", fontFamily: mono, fontWeight: "700" }}
          onClick={() => router.push("/")}
        >
          GET STARTED →
        </button>
      </nav>

      <div style={{ maxWidth: "760px", margin: "0 auto", padding: "3rem 1.25rem 6rem" }}>
        {/* Header */}
        <div style={{ marginBottom: "4rem" }}>
          <div style={{ fontSize: "0.55rem", letterSpacing: "0.25em", color: C.red, border: `1px solid rgba(220,38,38,0.3)`, padding: "0.25rem 0.7rem", display: "inline-block", marginBottom: "1rem" }}>HOW IT WORKS</div>
          <h1 style={{ fontSize: "clamp(2rem,5vw,3rem)", fontWeight: "700", lineHeight: 1.1, margin: "0 0 1rem" }}>
            Set it once.<br /><span style={{ color: C.red }}>Get mogged forever.</span>
          </h1>
          <p style={{ fontSize: "0.82rem", color: C.muted, lineHeight: "1.9", maxWidth: "520px", margin: 0 }}>
            MoggedAI works entirely over SMS. No app to open. No dashboard to check. Just your phone buzzing all day reminding you to actually do the things you said you would.
          </p>
        </div>

        {/* Steps */}
        <div style={{ display: "flex", flexDirection: "column", gap: "1px", background: C.border }}>
          {STEPS.map((step, i) => (
            <div key={step.n} style={{ background: C.card, padding: "2rem 1.5rem" }}>
              <div style={{ display: "flex", gap: "1.5rem", alignItems: "flex-start", flexWrap: "wrap" }}>
                {/* Step number */}
                <div style={{ fontSize: "0.65rem", color: C.red, fontWeight: "700", letterSpacing: "0.1em", minWidth: "28px", paddingTop: "2px" }}>{step.n}</div>

                {/* Content */}
                <div style={{ flex: 1, minWidth: "200px" }}>
                  <h2 style={{ fontSize: "1rem", fontWeight: "700", margin: "0 0 0.3rem", letterSpacing: "0.03em" }}>{step.title}</h2>
                  <div style={{ fontSize: "0.6rem", color: C.red, letterSpacing: "0.1em", marginBottom: "0.85rem" }}>{step.sub}</div>
                  {step.body.split("\n\n").map((para, j) => (
                    <p key={j} style={{ fontSize: "0.75rem", color: C.muted, lineHeight: "1.85", margin: j > 0 ? "0.6rem 0 0" : "0" }}>{para}</p>
                  ))}

                  {/* SMS example */}
                  {step.sms && (
                    <div style={{ marginTop: "1.25rem", background: "#080808", border: `1px solid ${C.border}`, borderRadius: "12px", padding: "1rem", display: "flex", flexDirection: "column", gap: "8px", maxWidth: "380px" }}>
                      <div style={{ fontSize: "0.45rem", color: C.red, letterSpacing: "0.2em", marginBottom: "4px" }}>MOGGEDAI</div>
                      {step.sms.from && (
                        <div style={{ background: "#141414", borderRadius: "8px 8px 8px 0", padding: "0.6rem 0.8rem" }}>
                          <div style={{ fontSize: "0.65rem", color: "#bbb", lineHeight: "1.55" }}>{step.sms.from}</div>
                        </div>
                      )}
                      {step.sms.reply && (
                        <div style={{ background: "rgba(220,38,38,0.12)", border: "1px solid rgba(220,38,38,0.2)", borderRadius: "8px 8px 0 8px", padding: "0.6rem 0.8rem", alignSelf: "flex-end", maxWidth: "85%" }}>
                          <div style={{ fontSize: "0.65rem", color: C.red }}>{step.sms.reply}</div>
                          <div style={{ fontSize: "0.42rem", color: "#555", textAlign: "right", marginTop: "4px" }}>you</div>
                        </div>
                      )}
                      {step.sms.followup && (
                        <div style={{ background: "#1a1a1a", border: `1px solid #222`, borderRadius: "8px 8px 8px 0", padding: "0.6rem 0.8rem" }}>
                          <div style={{ fontSize: "0.42rem", color: "#555", marginBottom: "4px", letterSpacing: "0.1em" }}>5 MIN LATER</div>
                          <div style={{ fontSize: "0.65rem", color: "#bbb", lineHeight: "1.55" }}>{step.sms.followup}</div>
                        </div>
                      )}
                      {step.sms.response && (
                        <div style={{ background: "#141414", borderRadius: "8px 8px 8px 0", padding: "0.6rem 0.8rem" }}>
                          <div style={{ fontSize: "0.65rem", color: "#bbb", lineHeight: "1.55", whiteSpace: "pre-line" }}>{step.sms.response}</div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
              {/* Divider line (not last) */}
              {i < STEPS.length - 1 && <div style={{ height: "1px", background: "#111", marginTop: "2rem", marginLeft: "44px" }} />}
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div style={{ textAlign: "center", marginTop: "4rem", padding: "2.5rem", background: C.card, border: `1px solid ${C.border}` }}>
          <p style={{ fontSize: "clamp(1rem,2.5vw,1.4rem)", fontWeight: "700", lineHeight: 1.4, marginBottom: "0.5rem" }}>
            Ready to stop making excuses?
          </p>
          <p style={{ fontSize: "0.72rem", color: C.muted, marginBottom: "1.75rem" }}>Takes 2 minutes to set up. Free to start.</p>
          <button
            style={{ background: C.red, border: "none", color: "#fff", padding: "1rem 2.5rem", fontSize: "0.82rem", letterSpacing: "0.15em", cursor: "pointer", fontFamily: mono, fontWeight: "700" }}
            onClick={() => router.push("/")}
          >
            GET MOGGED — IT&apos;S FREE →
          </button>
          <p style={{ fontSize: "0.55rem", color: "#1a1a1a", marginTop: "0.75rem" }}>US numbers only · Text STOP to unsubscribe anytime</p>
        </div>
      </div>
    </div>
  );
}
